sab/main/urls.py
from django.conf.urls.defaults import *
from main import views

urlpatterns = patterns(
    '',
    url(r'^$', views.index, name="index"),
    url(r'^donate/$', views.donate, name="donate"),
    url(r'^pledge/$', views.pledge, name="pledge"),
    url(r'^confirm_pledge/(?P<confirm_code>\w+)/$', 
        views.confirm_pledge, name="confirm_pledge"),
    url(r'^confirm_fail/(?P<confirm_code>\w+)/$', 
        views.confirm_fail, name="confirm_fail"),
    url(r'^closewindow/$',
        'django.views.generic.simple.direct_to_template',
        {'template': 'closewindow.html'}, name='closewindow'),
    url(r'^widget/$', views.widget, name='widget'),

)

sab/urls.py
from django.conf.urls.defaults import *
from django.contrib import admin
from django.conf import settings
from django.views.generic.simple import redirect_to

admin.autodiscover()


urlpatterns = patterns(
    '',
    (r'', include('main.urls', namespace='main')),
    url(r'^robots.txt', 'django.views.generic.simple.direct_to_template', 
        {'template': 'robots.txt', 'mimetype': 'text/plain'}),
    (r'^admin/doc/', include('django.contrib.admindocs.urls')),
    (r'^admin/', include(admin.site.urls)),
)

if settings.DEBUG:
    urlpatterns += patterns(
        '',
        (r'^site_media/(?P<path>.*)$', 'django.views.static.serve',
         {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
        (r'^favicon\.ico$', 'django.views.static.serve',
         {'document_root': settings.MEDIA_ROOT, 
          'path': 'images/favicon.ico', 
          'show_indexes': True}))

sab/main/models.py
from django.db import models

class Pledge(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    ip_address = models.CharField(max_length=32, blank=False)
    email = models.EmailField(unique=True, db_index=True)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    confirm_date = models.DateTimeField(null=True)
    confirm_code = models.CharField(
        max_length=255, blank=False, unique=True, db_index=True)

sab/main/forms.py
from django.forms import ModelForm
from django import forms
from main.models import Pledge
from uuid import uuid4

class PledgeForm(ModelForm):
    class Meta:
        model = Pledge
        fields = ('email', 'amount',)

    def save(self, request):
        ip_address = request.META.get('REMOTE_ADDR', 'no ip address')
        amount = self.cleaned_data['amount']
        obj, created = Pledge.objects.get_or_create(
            email=self.cleaned_data['email'],
            defaults = {
                'ip_address': ip_address,
                'amount': amount,
                'confirm_code': str(uuid4()).replace('-', '')})
        if not created:
            # TODO: maybe send alert
            obj.ip_address = ip_address
            obj.amount = amount
            obj.save()
        return obj

    def get_errors(self):
        from django.utils.encoding import force_unicode        
        output = {}
        for key, value in self.errors.items():
            output[key] = '/n'.join([force_unicode(i) for i in value])
        return output

sab/main/views.py
from django.core.mail import send_mail
from django.conf import settings
from django.http import HttpResponse
from django.template import RequestContext
from django.template.loader import render_to_string
from django.shortcuts import render_to_response, redirect
from django.core.urlresolvers import reverse
from django.core.exceptions import ObjectDoesNotExist
import django.utils.simplejson as json
from main.forms import PledgeForm
from main import models, count_cache
from boto.ses import SESConnection
from django.contrib.sites.models import Site
from django.utils.http import urlencode
from datetime import datetime

def _send_email(email, amount, confirm_code):
    if not settings.DEBUG:
        context = {
            'confirm_url': 'http://{0}{1}'.format(
                Site.objects.get_current().domain,
                reverse('main:confirm_pledge', args=[confirm_code])) }
        connection = SESConnection(
            aws_access_key_id=settings.AWS_ACCESS_KEY,
            aws_secret_access_key=settings.AWS_SECRET_KEY)
        connection.send_email(
            source="pledges@sponsorabigot.org",
            subject="Please confirm your pledge",
            body=render_to_string('pledge_email.html', context),
            to_addresses=[email],
            format='html',
            cc_addresses=['pledges@sponsorabigot.org'])
    else:
        print('Sent email to {0} about {1} with confirm code {2}'.format(
                email, amount, confirm_code))

def _add_amounts_to_context(ctx=None):
    if ctx is None:
        ctx = {}
    total_amount = count_cache.get_total_amount()
    amount_pct = max(5, min(100, int(100 * total_amount / settings.FUNDING_GOAL)))
    ctx.update({
            'amount': total_amount,
            'amount_goal': settings.FUNDING_GOAL,
            'amount_pct': amount_pct })
    return ctx

def index(request):
    return render_to_response(
        'index.html',
        _add_amounts_to_context(),
        context_instance=RequestContext(request))

def widget(request):
    return render_to_response(
        'widget.html',
        _add_amounts_to_context(),
        context_instance=RequestContext(request))

def pledge(request):
    form = PledgeForm(request.POST)
    if form.is_valid():
        pledge = form.save(request)
        _send_email(pledge.email,
                    pledge.amount,
                    pledge.confirm_code)
        output = dict(success=True)
    else:
        output = dict(success=False, errors=form.get_errors())
    return HttpResponse(json.dumps(output), 'text/javascript')

def donate(request):
    return render_to_response(
        'donate.html',
        _add_amounts_to_context({ 'form': PledgeForm() }),
        context_instance=RequestContext(request))

def confirm_pledge(request, confirm_code):
    try:
        pledge = models.Pledge.objects.get(confirm_code=confirm_code)
    except ObjectDoesNotExist:
        return redirect('main:confirm_fail', confirm_code=confirm_code)
    pledge.confirm_date = datetime.now()
    pledge.save()
    return render_to_response(
        'confirm.html',
        _add_amounts_to_context({ 'pledge': pledge }),
        context_instance=RequestContext(request))

def confirm_fail(request, confirm_code):
    return render_to_response(
        'confirm_fail.html',
        _add_amounts_to_context(),
        context_instance=RequestContext(request))

sab/templates/_follow_links.html
<div class="follow-links">
  <p>Follow Us</p>
  <a class="fb" href="http://facebook.com/sponsorabigot" target="fb">&nbsp;</a>
  <a class="tw" href="http://twitter.com/sponsorabigot" target="tw">&nbsp;</a>
</div>

sab/templates/_share.html
<p>Think this is awesome? We agree! Please tell others.</p>
<a class="share fb fb-sharedonation" href="javascript:void();"><span>Share on Facebook</span></a>
<a class="share twitter tw-sharedonation" href="javascript:void();"><span>Share on Twitter</span></a>
<div class="clear">&nbsp;</div>

sab/templates/base.html
{% load humanize %}

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:og="http://ogp.me/ns#"
      xmlns:fb="http://www.facebook.com/2008/fbml" 
      xml:lang="en" lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta property="og:title" content="Sponsor a Bigot"/>
    <meta property="og:type" content="cause"/>
    <meta property="og:url" content="http://sponsorabigot.org/"/>
    <meta property="og:image" content="{{MEDIA_URL}}images/fbimage.jpg"/>
    <meta property="og:site_name" content="Sponsor a Bigot"/>
    <meta property="fb:app_id" content="{{facebook_app_id}}"/>
    <meta property="og:description"
          content="Help us turn Westboro's protest of Liz Taylor's public funeral 
                   into a fundraising bonanza for the Elizabeth Taylor AIDS 
                   Foundation."/>
    <title>Sponsor a Bigot</title>
    <link rel="stylesheet" href="{{MEDIA_URL}}css/base.css"/>
    <link rel="stylesheet" href="{{MEDIA_URL}}css/amount_bar.css"/>
    {% block css %}{% endblock %}
    <!--[if IE]>
    <style>
      .sabpanel {
          background-color: transparent;
          filter: progid:DXImageTransform.Microsoft.gradient(startColorstr=#eef0f0f0 endColorstr=#eef0f0f0);
          -ms-filter: "progid:DXImageTransform.Microsoft.gradient(startColorstr=#eef0f0f0, endColorstr=#eef0f0f0)";
      }
    </style>
    <![endif]-->
  </head>
  <body>
    <div id="wrapper">
      <div id="header">
        <div class="main-content">
          <div id="headerright">
            <p>{{amount|intcomma}} of ${{amount_goal|intcomma}} raised</p>
            {% include "_amount_bar.html" %}
          </div>
          <h1><a href="http://sponsorabigot.org"><span>Sponsor a Bigot</span></a></h1>
        </div>
      </div>
      <div id="main" class="main-content">{% block content %}{% endblock %}</div>
      <div style="clear:both">&nbsp;</div>
      <div id="push">&nbsp;</div>
    </div>
    <div id="footer">
      <div class="main-content">
        <div id="footer-bg">&nbsp;</div>
        <div id="footer-bg2">&nbsp;</div>
        {% include "_follow_links.html" %}
        <div id="copyright">
          <span>&#169; 2011 Adam Duston. All rights reserved.</span>
        </div>
      </div>
    </div>
    <script type="text/javascript">
      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-21848784-1']);
      _gaq.push(['_trackPageview']);
      (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = 'http://www.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();
      var FACEBOOK_APP_ID = '{{facebook_app_id}}';
      var POPUP_REDIRECT_URL = 'http://sponsorabigot.org{% url main:closewindow %}';
      var FB_IMAGE = '{{MEDIA_URL}}images/fbimage.jpg';
      var TOTAL_AMOUNT = {{amount}};
      var TOTAL_AMOUNT_GOAL = {{amount_goal}};
    </script>
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.5.1/jquery.min.js"></script>
    {% block script %}{% endblock %}    
  </body>
</html>

sab/templates/closewindow.html
<html>
  <script>
    function main() {
      window.close();
    }
  </script>
  <body onload="main()">
    Completing...
  </body>
</html>

sab/templates/confirm.html
{% extends "base.html" %}

{% block script %}
<script type="text/javascript">
  var dollarAmount = {{pledge.amount}};
</script>
<script type="text/javascript" src="{{MEDIA_URL}}js/share.js"></script>
{% endblock %}

{% block css %}
<link rel="stylesheet" href="{{MEDIA_URL}}css/donate.css"/>
{% endblock %}

{% block content %}
<div id="pledgepanel" class="sabpanel">
  <p>
    Hi, you have pledged to donate ${{pledge.amount}} to the 
    Elizabeth Taylor AIDS Foundation for every hour Westboro 
    spends protesting Liz Taylor's funeral.
  </p>
  <p>
    Thank you.
  <p>
    {% include "_share.html" %}
</div>
{% endblock %}

sab/templates/confirm_fail.html
{% extends "base.html" %}

{% block content %}
Sorry, we don't recognize that confirmation code.
{% endblock %}

sab/templates/donate.html
{% extends "base.html" %}

{% block css %}
<link rel="stylesheet" href="{{MEDIA_URL}}css/donate.css"/>
{% endblock %}

{% block content %}
<div id="westboro">&nbsp;</div>
<div id="pledgepanel" class="sabpanel">
  <div id="firstPage">
    <h2>
      Donate to the Elizabeth Taylor AIDS Foundation for every hour they spend protesting.
    </h2>
    <p>
      Disgusted by Westboro? So are we. Help us turn their protest into a
      fundraising bonanza for the 
      <a href="http://elizabethtayloraidsfoundation.org/" target="etaf" class="link">Elizabeth Taylor AIDS Foundation</a>.
    </p>
    <form action="{% url main:pledge %}" method="post" id="pledge_form">
      {% csrf_token %}
      <div class="formrow">
        <label for="id_email">Email:</label>
        <div class="input-container">
          <div class="errormsg" style="display:none" id="email_errors"><div></div></div>
          {{form.email}}
        </div>
      </div>
      <div class="formrow">
        <label for="id_amount">
          For every hour Westboro protests Liz Taylor's memorial service,
          I pledge to donate to the <a href="http://www.elizabethtayloraidsfoundation.org/" target="etaf" class="link">Elizabeth Taylor AIDS Foundation</a>:
        </label>
        <div class="input-container">
          <div class="errormsg" style="display:none" id="amount_errors"><div></div></div>
          <div id="dollar_sign">$</div>
          {{form.amount}}
        </div>
      </div>
      <div class="button-container">
        <a class="button" href="javascript:void();"><span id="submit_label">Submit</span></a>
        <div class="clear">&nbsp;</div>
      </div>
    </form>
  </div>
  <div id="secondPage" style="display:none">
    <h2>Thank you for being part of the solution.</h2>
    <p>
      We have sent you an email confirmation. Please click on the link 
      in the email to confirm that your email address is real.
    </p>
    {% include "_share.html" %}
  </div>
</div>
<div id="rightside">
  <div class="sabpanel">
    <h2>Since they're going to show up anyway, we hope they stay as long as possible.</h2>
    <p>For every hour WBC spends protesting, more money is going to a great foundation. During the service, we'll be sending out live updates with the amount of money they've raised.</p>
    {% include "_follow_links.html" %}
    <div class="spacer">&nbsp;</div>
  </div>
</div>
{% endblock %}

{% block script %}
<script type="text/javascript" src="{{MEDIA_URL}}js/share.js"></script>
<script type="text/javascript" src="{{MEDIA_URL}}js/jquery.form.js"></script>
<script type="text/javascript" src="{{MEDIA_URL}}js/donate.js"></script>
{% endblock %}

sab/templates/donate0.html
{% extends "base.html" %}

{% block css %}
<link rel="stylesheet" href="{{MEDIA_URL}}css/donate0.css"/>
{% endblock %}

{% block script %}
<script type="text/javascript" src="{{MEDIA_URL}}js/share.js"></script>
<script type="text/javascript" src="{{MEDIA_URL}}js/jquery.watermark.min.js"></script>
<script type="text/javascript" src="{{MEDIA_URL}}js/jquery.form.js"></script>
<script type="text/javascript" src="{{MEDIA_URL}}js/donate0.js"></script>
{% endblock %}

{% block content %}
<h1>Since they're going to show up anyway, we hope they stay as long as possible.</h1>
<div class="explanation">
  <div class="round donate">
    <h2>Donate to the Elizabeth Taylor AIDS Foundation for every hour they spend protesting.</h2>
    <p>Disgusted by Westboro? So are we! Help us turn their protest into a fundraising bonanza for the <a href="http://www.elizabethtayloraidsfoundation.org/" target="etaf">Elizabeth Taylor AIDS Foundation</a>.</p>
  </div>
  <div class="round encourage">
    <h2>Planning to be at the funeral? </h2>
    <p>For every hour WBC spends protesting, more money is going to a great foundation! During the service, we'll be sending out live tweets with the amount of money they've raised.</p>
    <p>Cheer them on to protest for as long as possible!</p>
  </div>
</div>
<div class="pledge">
  <div id="firstPage">
    <form action="{% url main:pledge %}" method="post" id="pledge_form">
      {% csrf_token %}
      <div class="errorlist" id="email_errors"></div>
      <div class="formrow"><label for="id_email">My email is:</label>{{form.email}}</div>
      <div class="errorlist" id="amount_errors"></div>
      <div class="formrow">
        <label for="id_amount">
          For every hour Westboro protests Liz Taylor's memorial service,
          I pledge to donate to the <a href="http://www.elizabethtayloraidsfoundation.org/" target="etaf">Elizabeth Taylor AIDS Foundation</a>:
        </label>
        <div>
          <div id="dollar_sign">$</div>
          {{form.amount}}
        </div>
      </div>
      <p>
        <a href="#" class="button"><span id="submit_label">Submit</span></a>
      </p>
    </form>
  </div>
  <div id="secondPage" style="display:none">
    <p>
      We have sent you an email confirmation. Please click on the link 
      in the email to confirm that your email address is real.
    </p>
    {% include "_share.html" %}
  </div>
</div>
{% endblock %}

sab/templates/index.html
{% extends "base.html" %}

{% block css %}
<link rel="stylesheet" href="{{MEDIA_URL}}css/index.css"/>
{% endblock %}

{% block script %}
<script type="text/javascript" src="{{MEDIA_URL}}js/share.js"></script>
{% endblock %}

{% block content %}
<div id="westboro">&nbsp;</div>
<div class="sabpanel" id="invitationpanel">
  <h2>Westboro is planning to protest Elizabeth Taylor's public memorial service.</h2>
  <p>
    Pledge a donation to the Elizabeth Taylor AIDS Foundation for every hour they spend protesting.
  </p>
  <a class="button" href="{% url main:donate %}"><span>I'm in</span></a>
  <div class="share">
    <a class="share fb fb-sharesite" href="javascript:void();"><span>Share on Facebook</span></a>
    <a class="share twitter tw-sharesite" href="javascript:void();"><span>Share on Twitter</span></a>
  </div>
  <div class="clear">&nbsp;</div>
</div>
{% endblock %}

sab/templates/index0.html
{% extends "base.html" %}

{% block css %}
<link rel="stylesheet" href="{{MEDIA_URL}}css/index0.css"/>
{% endblock %}

{% block content %}
<h1>Westboro Baptist Church plans to protest Elizabeth Taylor's public memorial service.</h1>
<img class="wbc" src="{{MEDIA_URL}}images/wbc-short.jpg" alt="WBC earning money"/>
<h1>Donate to the Elizabeth Taylor AIDS Foundation for every minute they spend protesting.</h1>
<div class="main">
  <div class="side donate">
    <h2>Turn WBC into awesome fundraisers!</h2>
    <p>Disgusted by Westboro? So are we! Turn their protest into a fundraising bonanza for the Elizabeth Taylor AIDS Foundation!</p>
    <a href="{% url main:donate %}">I'm Interested</a>
  </div>
  <div class="side encourage">
    <h2>Planning to be at the funeral? </h2>
    <p>For every minute WBC spends protesting, more money is going to a great foundation! During the service, we'll be sending out live tweets with the amount of money they've raised.</p>
    <p>Cheer them on to protest for as long as possible!</p>
  </div>
</div>

{% endblock %}

sab/templates/index1.html
{% extends "base.html" %}

{% block css %}
<link rel="stylesheet" href="{{MEDIA_URL}}css/index1.css"/>
{% endblock %}

{% block content %}

<div class=block>
These bigots<br>
<img src='{{MEDIA_URL}}images/wbc2.jpg' style="width: 336px; height: 175px; padding: 5px; margin: 0 auto;"></img>
<br>
are protesting
Elizabeth Taylor’s funeral.
<br>
<div class=h2>For every hour they protest, you can</div>

<div style="clear: both;"></div>

<a class=some-button href="#"><span>Pledge to Liz Taylor’s<br> AIDS foundation</span></a>

</div>

{% endblock %}

sab/templates/index2.html
{% extends "base.html" %}

{% block css %}
<link rel="stylesheet" href="{{MEDIA_URL}}css/index2.css"/>
{% endblock %}

{% block content %}
<h1>Westboro Baptist Church plans to protest Elizabeth Taylor's public memorial service.</h1>
<img class="wbc" src="{{MEDIA_URL}}images/wbc-short.jpg" alt="WBC earning money"/>
<h1 class="sub">We're hoping they stay out there as long as possible!</h1>
<div class="main">
  <div class="side donate">
    <h2>Donate to the Elizabeth Taylor AIDS Foundation for every minute they spend protesting.</h2>
    <p>Disgusted by Westboro? So are we! Turn their protest into a fundraising bonanza for the Elizabeth Taylor AIDS Foundation!</p>
    <a href="{% url main:donate %}">I'm Interested</a>
  </div>
  <div class="side encourage">
    <h2>Planning to be at the funeral? </h2>
    <p>For every minute WBC spends protesting, more money is going to a great foundation! During the service, we'll be sending out live tweets with the amount of money they've raised.</p>
    <p>Cheer them on to protest for as long as possible!</p>
  </div>
</div>

{% endblock %}

sab/templates/pledge_email.html
<html>
<body>
  <p>
    Please confirm your pledge to donate to the Elizabeth Taylor 
    AIDS Foundation by clicking here: <a href="{{confirm_url}}">{{confirm_url}}</a>.
  </p>
  <p>If you did not pledge to donate to the Elizabeth Taylor AIDS Foundation, please
    let us know at 
    <a href="mailto:pledges@sponsorabigot.org">pledges@sponsorabigot.org</a>.
  </p>
</body>
</html>

sab/templates/widget.html
{% load humanize %}

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:og="http://ogp.me/ns#"
      xmlns:fb="http://www.facebook.com/2008/fbml" 
      xml:lang="en" lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>Sponsor a Bigot</title>
    <link rel="stylesheet" href="{{MEDIA_URL}}css/base.css"/>
    <link rel="stylesheet" href="{{MEDIA_URL}}css/amount_bar.css"/>
    <link rel="stylesheet" href="{{MEDIA_URL}}css/widget.css"/>
  </head>
  <body>
    <div class="widget-container">
      <h2>Westboro will protest Elizabeth Taylor's public memorial service.</h2>
      <p>Pledge a donation to the Elizabeth Taylor AIDS Foundation for every hour they spend protesting.</p>
      {% include "_amount_bar.html" %}
      <p class="amount">{{amount|intcomma}} of ${{amount_goal|intcomma}} raised so far (per hour)</p>
      <a class="button" target="_blank" href="http://sponsorabigot.org"><span>I'm in</span></a>
    </div>
  </body>
</html>